name: DCO Check

on:
  workflow_call:

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check signoff
        run: |
          git log origin/${{ github.base_ref }}..HEAD \
            --format='%B' | grep -q "Signed-off-by:" \
          || (echo "Missing DCO Signoff" && exit 1)
